### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-leaflet#2]
How do we have to handle the `LICENSE` file @lseelenbinder ?

**Comment by lseelenbinder** [comment]
Hi @wipfli—apologies for the delay. I was out of office.

I think minimally we will need to:
- Add a new license for code in fork after forking (probably MIT, since that's what we use elsewhere).
- Retain the license for the Mapbox / previous contributors in the same file.
- Update the README to acknowledge and thank Mapbox (and point to the original repo).

@nyurik Am I missing anything?

**Comment by nyurik** [comment]
I will need to double check if it is possible to convert ISC license into MIT. While they are very similar, the lawyers might disagree. I don't know how it should be worded.

**Comment by nyurik** [comment]
I have spoken with some experts, and it seems the easiest course of action is just to add another copyright line above Mapbox's, and keep the ISC line.

The top line would say be `Copyright (c) 2021 MapLibre contributors`, followed by the mapbox's copyright.

**Comment by lseelenbinder** [comment]
Sounds good, @nyurik. Thanks!

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-leaflet/pull/8
